import React, { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import './ScatteredImages.css';

// Register ScrollTrigger plugin and attach to window for debugging
gsap.registerPlugin(ScrollTrigger);

// Make GSAP available globally for debugging
if (typeof window !== 'undefined') {
  window.gsap = gsap;
    window.ScrollTrigger = ScrollTrigger;
    }


    const ScatteredImages = () => {
      const containerRef = useRef(null);
        const imageRefs = useRef([]);

          // Image URLs from uploaded assets
            const images = [
                // Left side images (2 images)
                    {
                          url: "https://customer-assets.emergentagent.com/job_smooth-scroll-17/artifacts/fumq7h3r_Screenshot%202025-10-01%20021056.png",
                                position: { top: '20%', left: '5%', rotate: '-12deg' },
                                      side: 'left'

                                          },
                                              {
                                                    url: "https://customer-assets.emergentagent.com/job_smooth-scroll-17/artifacts/w15cm22k_Screenshot%202025-10-01%20021120.png",
                                                          position: { top: '55%', left: '8%', rotate: '0deg' }, // No tilt for second left image
                                                                side: 'left'
                                                                    },
                                                                        // Right side images (3 images)
                                                                            {
                                                                                  url: "https://customer-assets.emergentagent.com/job_smooth-scroll-17/artifacts/jvmwbxaj_Screenshot%202025-10-01%20021130.png",
                                                                                        position: { top: '15%', right: '12%', rotate: '8deg' },
                                                                                              side: 'right'
                                                                                                  },
                                                                                                      {
                                                                                                            url: "https://customer-assets.emergentagent.com/job_smooth-scroll-17/artifacts/fn5fp6c5_Screenshot%202025-10-01%20021144.png",
                                                                                                                  position: { top: '45%', right: '8%', rotate: '0deg' },
                                                                                                                        side: 'right'
                                                                                                                            },
                                                                                                                                {
                                                                                                                                      url: "https://customer-assets.emergentagent.com/job_smooth-scroll-17/artifacts/8khxffu5_Screenshot%202025-10-01%20021200.png",
                                                                                                                                            position: { top: '60%', right: '28%', rotate: '-12deg' },
                                                                                                                                                  side: 'right'
                                                                                                                                                      }
                                                                                                                                                        ];

                                                                                                                                                          useEffect(() => {
                                                                                                                                                              if (!containerRef.current) {
                                                                                                                                                                    console.warn('ScatteredImages: Container ref not available');
                                                                                                                                                                          return;
                                                                                                                                                                              }

                                                                                                                                                                                  console.log('ScatteredImages: Initializing GSAP animations for', images.length, 'images');

                                                                                                                                                                                      try {
                                                                                                                                                                                            // Clear any existing ScrollTriggers
                                                                                                                                                                                                  ScrollTrigger.getAll().forEach(trigger => trigger.kill());

                                                                                                                                                                                                        // Create timeline for each image
                                                                                                                                                                                                              imageRefs.current.forEach((imageRef, index) => {
                                                                                                                                                                                                                      if (!imageRef) {
                                                                                                                                                                                                                                console.warn(`ScatteredImages: Image ref ${index} not available`);
                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                          const image = images[index];
                                                                                                                                                                                                                                                                  const isLeftSide = image.side === 'left';
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                  console.log(`Setting up animation for image ${index} (${isLeftSide ? 'left' : 'right'} side)`);

                                                                                                                                                                                                                                                                                          // Set initial state - hidden initially
                                                                                                                                                                                                                                                                                                  gsap.set(imageRef, {
                                                                                                                                                                                                                                                                                                            scale: 1,
                                                                                                                                                                                                                                                                                                                      x: 0,
                                                                                                                                                                                                                                                                                                                                y: 0,
                                                                                                                                                                                                                                                                                                                                          opacity: 0, // Start hidden
                                                                                                                                                                                                                                                                                                                                                    rotation: parseFloat(image.position.rotate),
                                                                                                                                                                                                                                                                                                                                                              transformOrigin: 'center center'
                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                // Entrance animation with 2 second delay
                                                                                                                                                                                                                                                                                                                                                                                        gsap.to(imageRef, {
                                                                                                                                                                                                                                                                                                                                                                                                  opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                            duration: 0.8,
                                                                                                                                                                                                                                                                                                                                                                                                                      delay: 2 + (index * 0.1), // 2 second base delay + staggered timing
                                                                                                                                                                                                                                                                                                                                                                                                                                ease: "power2.out"
                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                        // Create scroll-triggered animation that works across entire page
                        gsap.timeline({
                          scrollTrigger: {
                            trigger: document.body,
                            start: "top top",
                            end: "400vh top", // Much longer duration for slower, smoother animation
                            scrub: 3, // Higher scrub value for buttery smooth following
                            ease: "power2.out", // Smooth easing
                            onUpdate: (self) => {
                                const progress = self.progress;
                                
                                // Check if this is the second left image (index 1)
                                if (index === 1) {
                                    // Custom animation for second left image: scale out and move left
                                    const scale = 0.9 + (progress * 1.5); // Start at 90% and grow to 2.4x (more dramatic scaling)
                                    const moveDistance = progress * -600; // Move left (negative value, more distance)
                                    const opacity = progress < 0.8 ? 1 : 1 - ((progress - 0.8) / 0.2); // Fade out later
                                    
                                    // Apply custom transformations for second left image
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistance, // Move left in straight line
                                        y: 0, // No vertical movement
                                        opacity: Math.max(0, opacity),
                                        rotation: 0, // No rotation - stays straight
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                } else if (index === 3) {
                                    // Custom animation for middle right image: scale up and move right
                                    const scale = 1 + (progress * 1.8); // Start at 100% and grow to 2.8x
                                    const moveDistance = progress * 400; // Move right (positive value)
                                    const opacity = progress < 0.75 ? 1 : 1 - ((progress - 0.75) / 0.25); // Fade out later
                                    
                                    // Apply custom transformations for middle right image
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistance, // Move right in straight line
                                        y: 0, // No vertical movement
                                        opacity: Math.max(0, opacity),
                                        rotation: 0, // No rotation - stays straight
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                } else if (index === 2) {
                                    // Custom animation for first right image: slight zoom and move diagonally up-right off screen
                                    const scale = 1 + (progress * 0.8); // Start at 100% and grow to 1.8x (slight zoom)
                                    const moveDistanceX = progress * 500; // Move right off screen
                                    const moveDistanceY = progress * -350; // Move up off screen (negative value for upward)
                                    const opacity = progress < 0.65 ? 1 : 1 - ((progress - 0.65) / 0.35); // Fade out gradually
                                    
                                    // Apply custom transformations for first right image
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistanceX, // Move right off screen
                                        y: moveDistanceY, // Move up off screen (diagonal path)
                                        opacity: Math.max(0, opacity),
                                        rotation: parseFloat(image.position.rotate), // Keep original rotation
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                } else if (index === 4) {
                                    // Custom animation for third right image: move diagonally down-right off screen (no scaling)
                                    const scale = 1; // Keep original size, no scaling
                                    const moveDistanceX = progress * 600; // Move right off screen
                                    const moveDistanceY = progress * 400; // Move down off screen
                                    const opacity = progress < 0.6 ? 1 : 1 - ((progress - 0.6) / 0.4); // Fade out earlier
                                    
                                    // Apply custom transformations for third right image
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistanceX, // Move right off screen
                                        y: moveDistanceY, // Move down off screen (diagonal path)
                                        opacity: Math.max(0, opacity),
                                        rotation: parseFloat(image.position.rotate), // Keep original rotation
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                } else if (index === 0) {
                                    // Custom animation for first left image: minimal scaling, move left with rotation
                                    const scale = 1 + (progress * 0.2); // Much smaller scaling (only 1.2x instead of 2.2x)
                                    const moveDistance = progress * -300; // Move left
                                    
                                    // Much smoother fade out - start fading at 70% and fade gradually over 30%
                                    let opacity;
                                    if (progress < 0.7) {
                                        opacity = 1;
                                    } else {
                                        const fadeProgress = (progress - 0.7) / 0.3;
                                        opacity = 1 - Math.pow(fadeProgress, 2);
                                    }
                                    
                                    // Apply custom transformations for first left image
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistance,
                                        opacity: Math.max(0, opacity),
                                        rotation: parseFloat(image.position.rotate) + (progress * -20), // Rotate left
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                } else {
                                    // Default animation for remaining images
                                    const scale = 1 + (progress * 1.2);
                                    const moveDistance = progress * (isLeftSide ? -300 : 300);
                                    
                                    // Much smoother fade out - start fading at 70% and fade gradually over 30%
                                    let opacity;
                                    if (progress < 0.7) {
                                        opacity = 1;
                                    } else {
                                        const fadeProgress = (progress - 0.7) / 0.3;
                                        opacity = 1 - Math.pow(fadeProgress, 2);
                                    }
                                    
                                    // Apply default transformations
                                    gsap.set(imageRef, {
                                        scale: scale,
                                        x: moveDistance,
                                        opacity: Math.max(0, opacity),
                                        rotation: parseFloat(image.position.rotate) + (progress * (isLeftSide ? -20 : 20)),
                                        zIndex: 25000 + (index * 100),
                                        ease: "power2.out"
                                    });
                                }
                            }
                          }
                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log('ScatteredImages: All animations initialized successfully');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('Active ScrollTriggers:', ScrollTrigger.getAll().length);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.error('ScatteredImages: Error initializing animations:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Cleanup function
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ScrollTrigger.getAll().forEach(trigger => trigger.kill());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [images]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div ref={containerRef} className="scattered-images-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {images.map((image, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={index}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ref={el => imageRefs.current[index] = el}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`scattered-image scattered-image-${index + 1}`}
                                              style={{
                                      position: 'absolute',
                                                  ...image.position,
                                                              transform: `rotate(${image.position.rotate})`,
                                                                          zIndex: 25000 + (index * 100), // Extremely high base z-index
                                                                                      '--rotate': image.position.rotate,
                                                                                                  '--float-delay': `${index * 0.5}s`
                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="image-wrapper">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src={image.url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alt={`Nothing showcase ${index + 1}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="scattered-img"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loading="lazy"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ScatteredImages;